done

diff --git a/roboshop/component/mysqqql b/roboshop/component/mysqqql
--- a/roboshop/component/mysqqql
+++ b/roboshop/component/mysqqql
@@ -3,9 +3,25 @@
 user_id=$(id -u)
 component=mysql
 
+status() {
+    if [ $? -eq 0 ]; then
+      echo -e "\e[32m sucess"
+    else
+      echo -e "\e[33 failure\e[0m"   
+    fi
+}
+
 echo -e "\e[32m check wheather user is root or not"
 if [ $user_id -ne 0 ]; then 
   echo -e "\e[33m you needs to be perform as root user \e[0m"
   echo -e "EXAMPLE  sudo <file_name>"
   exit 1
 fi
+
+echo -n "installing my-sql repo:"
+
+curl -s -L -o /etc/yum.repos.d/mysql.repo https://raw.githubusercontent.com/stans-robot-project/mysql/main/mysql.repo
+yum install mysql-community-server -y
+systemctl enable mysqld 
+systemctl start mysqld
+status $?
