done

diff --git a/roboshop/component/use b/roboshop/component/use
--- a/roboshop/component/use
+++ b/roboshop/component/use
@@ -1,74 +1,65 @@
+#!/bin/bash
 
 user_id=$(id -u)
-component=user
-appuser=roboshop
+component="user"
+appuser="roboshop"
 log="/tmp/${component}.log"
 
 if [ $user_id -ne 0 ]; then
-  echo -e "\e[32m script is executed by the root user or with sudo privilege \e[0m"
+  echo -e "\e[32mScript must be executed by the root user or with sudo privileges\e[0m"
   exit 1
 fi
 
-statusfunction(){
-
+statusfunction() {
     if [ $? -eq 0 ]; then
-       echo -e "\e[33m sucessfully installed \e[0m"
+       echo -e "\e[33mSuccessfully installed\e[0m"
     else
-       echo -e "\e[31m failed \e[0m"  
+       echo -e "\e[31mInstallation failed\e[0m"
        exit 1
     fi
 }
 
-echo -e "\e[35m configuring t}${component} \e[0m"
+echo -e "\e[35mConfiguring ${component}\e[0m"
 
-echo -n "installing ${component} :"
+echo -n "Installing ${component}: "
 curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
-statusfunction $?
+statusfunction
 
-echo -n "installing Nodejs :"
+echo -n "Installing Node.js: "
 yum install nodejs -y
-statusfunction $?
+statusfunction
 
 id ${appuser} &>> ${log}
 if [ $? -ne 0 ]; then
-  echo -n "creating application user account :"
-  useradd roboshop
-  statusfunction $?
+  echo -n "Creating application user account: "
+  useradd ${appuser}
+  statusfunction
 fi    
 
-echo -n "downlaoding the ${component} : "
+echo -n "Downloading the ${component}: "
 curl -s -L -o /tmp/user.zip "https://github.com/stans-robot-project/user/archive/main.zip"
-unzip -o /tmp/user.zip >>${log}
-statusfunction $?
+unzip -o /tmp/user.zip >> ${log}
+statusfunction
 
-echo -n "copying the ${component} to ${appuser} home diectory: "
-# cd /home/${appuser}/
-# rm -rf ${component} >> ${log}
-# unzip -o /tmp/${component}.zi
-cd /home/roboshop
-statusfunction $?
-
-echo -n "changing the ownership : "
+echo -n "Copying the ${component} to ${appuser} home directory: "
+cd /home/${appuser} || exit 1
 mv ${component}-main ${component}
 chown -R ${appuser}:${appuser} /home/${appuser}/${component}/
-statusfunction $?
+statusfunction
 
-echo -n "generating the ${component} artifacts :"
+echo -n "Generating the ${component} artifacts: "
 cd /home/${appuser}/${component}/
 npm install 
-statusfunction $?
+statusfunction
 
-echo -n "updating the ${component} systemfile "
+echo -n "Updating the ${component} systemd file: "
 sed -i "s/MONGO_ENDPOINT/mongodb.roboshop/"  /home/roboshop/user/systemd.service
 sed -i "s/REDIS_ENDPOINT/redis.roboshop/"  /home/roboshop/user/systemd.service
-
 mv /home/roboshop/user/systemd.service /etc/systemd/system/user.service
-statusfunction $?
+statusfunction
 
-
-echo -n "starting the user service: "
+echo -n "Starting the user service: "
 systemctl daemon-reload
 systemctl start user
-systemctl restart user
-systemctl status user 
-statusfunction $?
+systemctl enable user
+statusfunction
